PADV 888 - Sidebar styling fixes
Pearson-Advance/frontend-app-sidebar-navigation pull request #7
Opened 2023-12-04 17:37 UTC by alexjmpb

## Description:

This PR aims to fix various styles in the sidebar navigation that may affect the user experience.

## Changes Made

- [x] Align text to left inside sequence text.
- [x] Improve loading screen.
- [x] Improve error screen.

## Screenshots

### Text align

#### Before

![Screenshot from 2023-12-04 12-27-03](https://github.com/Pearson-Advance/frontend-app-sidebar-navigation/assets/62396424/b410d4f0-766d-4690-9715-14377762af22)

#### After

![Screenshot from 2023-12-04 12-26-22](https://github.com/Pearson-Advance/frontend-app-sidebar-navigation/assets/62396424/cf09df56-685d-4173-a278-f9537e3f6724)

### Loading screen

#### Before
![Screenshot from 2023-12-04 12-27-10](https://github.com/Pearson-Advance/frontend-app-sidebar-navigation/assets/62396424/69e094d2-6e71-4200-80f2-a1f5e9df6c02)

#### After 

![Screenshot from 2023-12-04 12-28-39](https://github.com/Pearson-Advance/frontend-app-sidebar-navigation/assets/62396424/8cd75480-34e5-4312-b4a3-8a9589ef3a26)

### Error message

#### Before

![Screenshot from 2023-12-04 12-27-35](https://github.com/Pearson-Advance/frontend-app-sidebar-navigation/assets/62396424/c748545a-47e5-4d53-b404-205a24febe49)

#### After

![Screenshot from 2023-12-04 12-28-54](https://github.com/Pearson-Advance/frontend-app-sidebar-navigation/assets/62396424/c6804947-3159-45df-b344-859e749a0eec)

## Reviewers:

- [ ] @AuraAlba 
- [ ] @anfbermudezme

2023-12-04 17:59 UTC, AuraAlba requested changes

2023-12-04 17:59 UTC, AuraAlba commented on src/index.scss
> +  aside nav {
It's a good practice use class element instead of element for styles

2023-12-04 21:19 UTC, AuraAlba approved these changes

2023-12-05 15:05 UTC, Jacatove reviewed
The spinner is far better than the "Loading" text but I wonder if it is not a big effort use the spinner here
![image](https://github.com/Pearson-Advance/frontend-app-sidebar-navigation/assets/40271196/bed8ecc2-df3b-4944-bf55-15d1df09ae84)
and only open the sidebar when it has its content?. This is just an observation. What are your thought?.

2023-12-05 15:13 UTC, alexjmpb commented
> The spinner is far better than the "Loading" text but I wonder if it is not a big effort use the spinner here ![image](https://private-user-images.githubusercontent.com/40271196/288083243-bed8ecc2-df3b-4944-bf55-15d1df09ae84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODkxNDQsIm5iZiI6MTcwMTc4ODg0NCwicGF0aCI6Ii80MDI3MTE5Ni8yODgwODMyNDMtYmVkOGVjYzItZGYzYi00OTQ0LWJmNTUtMTVkMWRmMDlhZTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE1MDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3N2U2ZmMxMGQ1YjU3Zjg3NjM1NjhmZjYzYzAzZTFlYWMwZmFhZGFkMDNiMzEzN2Y3M2MwNjczZDFkNzI5ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YbL6iB9RDk7xtSonlIcGnLUddcip1N3MdbHNUaypX8s) and only open the sidebar when it has its content?. This is just an observation. What are your thought?.

The problem is that in this case we would have to change the learning MFE, since the button belongs there. I was thinking to do this when adding the disable sidebar functionality.

2023-12-05 15:14 UTC, Jacatove approved these changes

2023-12-05 22:20 UTC, merged